package GUI;

import DAO.LibroJpaController;
import bibliotecafusm.ControladorConsulta;
import bibliotecafusm.Libro;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.List;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 *
 * @author Paulker
 */
public class Loading extends javax.swing.JPanel {

    private LibroJpaController librosjpa;
    private ControladorConsulta controlador;

    public Loading(ControladorConsulta controlador) {
        initComponents();
        this.controlador = controlador;
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BibliotecaFUSMPU");
        librosjpa = new LibroJpaController(emf);
        this.BarraProgreso.setStringPainted(true);
        this.BarraProgreso.setMinimum(0);
        this.setVisible(true);
    }

    public Controlador getControladorListener() {
        return new Controlador();
    }

    public ControladorConsulta getControlador(){
        return this.controlador;
    }

    public class Controlador implements ActionListener {

        public void actionPerformed(ActionEvent evt) {
            new Thread(new Hilo()).start();
        }

    }

    public class Hilo implements Runnable {

        public void run() {
            Logger logger = Logger.getLogger("MJZLog");
            FileHandler fh;
//            Lo del log
            try {
                fh = new FileHandler("d:\\log\\biblioteca_Fusm.log", true);
                SimpleFormatter formatter = new SimpleFormatter();
                fh.setFormatter(formatter);
                logger.addHandler(fh);
                logger.setLevel(Level.ALL);

            } catch (IOException e) {
                System.out.println("No se pudo escribir el LOG");
            }
            System.out.println("-----------------Aqui se ca a comenzar a leer los libros");
                    
            controlador.setLibrosBD(librosjpa.findLibros(BarraProgreso));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BarraProgreso = new javax.swing.JProgressBar();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cargando...");

        BarraProgreso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BarraProgreso, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BarraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BarraProgreso;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
