/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.PrestamoLibroJpaController;
import DAO.UsuarioJpaController;
import bibliotecafusm.PrestamoLibro;
import bibliotecafusm.Usuario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author Jhon Alex
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    private UsuarioJpaController usuariosjpa;    
    private Principal panelprinciapl;
    
    

    public Login(Principal pPanel) {
   
        this.panelprinciapl = pPanel;
        
        
        this.setTitle("Sistema Gestion Prestamos - Biblioteca FUSM Palmira"); 
        
        initComponents();
        
        
        // mensaje correo
        mensage1.setVisible(false);
        mensage2.setVisible(false);
        
        
        // instancia objeto que va guardar la info a la base de datos :: usuariojpa
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BibliotecaFUSMPU");
        usuariosjpa = new UsuarioJpaController(emf);


        jPasswordField1.addKeyListener(new KeyListener(){

            @Override
            public void keyTyped(KeyEvent ke) {
            }

            @Override
            public void keyPressed(KeyEvent ke) {
                if(ke.getKeyCode()==KeyEvent.VK_ENTER){
                    validarLogeo ();                   
                }    
            }

            @Override
            public void keyReleased(KeyEvent ke) {
            }
            
        });
        
        jTextField1.addKeyListener(new KeyListener(){

            @Override
            public void keyTyped(KeyEvent ke) {
            }

            @Override
            public void keyPressed(KeyEvent ke) {
                if(ke.getKeyCode()==KeyEvent.VK_ENTER){
                    validarLogeo ();                   
                }    
            }

            @Override
            public void keyReleased(KeyEvent ke) {
            }
            
        });
        
        
        
        jComboBox1.addKeyListener(new KeyListener(){

            @Override
            public void keyTyped(KeyEvent ke) {
            }

            @Override
            public void keyPressed(KeyEvent ke) {
                if(ke.getKeyCode()==KeyEvent.VK_ENTER){
                    validarLogeo ();                   
                }    
            }

            @Override
            public void keyReleased(KeyEvent ke) {
            }
            
        });
        

    }

  
    public void validarLogeo (){
        
        mensage1.setText("Cuenta de correo "+ jComboBox1.getSelectedItem().toString()+" No registrada");
        
        mensage1.setVisible(false);
        mensage2.setVisible(false);
       
        
        String mailUser = jTextField1.getText();
        String passUser = jPasswordField1.getText();
        String tipoUser = jComboBox1.getSelectedItem().toString();
    
        Usuario userValid = null;

        
    if(jTextField1.getText().equals("".trim())){       // si esta en blanco el correo
        
        JOptionPane.showMessageDialog(null, "Debe completar el campo Email");
    }else if(passUser.equals("".trim())){ // si esta en blanco el password
        JOptionPane.showMessageDialog(null, "Debe completar el campo Password");        
    
    }else{    
        
        if (!validacionCorreo (mailUser, tipoUser )) {
            mensage1.setVisible(true);  
        }else{
        
            if (validacionPass(mailUser, passUser)) {
                
                userValid = buscarUsuarioxCorreo(mailUser);
 
         
                

                panelprinciapl.setUsuario(userValid);

         
                jTextField1.setText("");
                jPasswordField1.setText("");
                        
                
     
                this.setVisible(false);
                panelprinciapl.setVisible(true);
                
            } else {
                mensage2.setVisible(true);
            }
        }
    }
    }
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        mensage1 = new javax.swing.JLabel();
        mensage2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 900, 600));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jTextField1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(490, 380, 360, 30);

        jButton1.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/btn_ini.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(560, 500, 230, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Docente", "Admin" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(620, 330, 110, 20);

        mensage1.setForeground(new java.awt.Color(255, 51, 51));
        mensage1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mensage1.setText("Cuenta de correo no registrada");
        getContentPane().add(mensage1);
        mensage1.setBounds(600, 360, 250, 14);

        mensage2.setForeground(new java.awt.Color(255, 51, 51));
        mensage2.setText("Password incorrecto");
        getContentPane().add(mensage2);
        mensage2.setBounds(720, 430, 130, 14);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(490, 450, 360, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/backfusmlogin.png"))); // NOI18N
        jLabel1.setText("                ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -1, 1350, 691);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    // BTN INICIAR SESION
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        validarLogeo ();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public boolean validacionCorreo (String srtCorreo, String strTipoUser){
        
        boolean exist = false;
       
        for (Usuario u : usuariosjpa.findUsuarioEntities()) {
            
            if (u.getEmail().equals(srtCorreo)) {
                if(u.getTipoUsuario().equals(strTipoUser)){
                      exist = true;
                }
            }
        }       
      return exist;  
    }
    
    public boolean validacionPass (String srtCorreo, String srtPass){
        
        boolean valido = false;
       
        for (Usuario u : usuariosjpa.findUsuarioEntities()) {
            
            if (u.getPassword().equals(srtPass)) {
                
                if(u.getEmail().equals(srtCorreo)){                 
                        valido = true;                  
                }   
            }
        }       
      return valido;  
    }
    

    
    public Usuario buscarUsuarioxCorreo(String srtCorreo){
        Usuario user =  new Usuario();

        for (Usuario u : usuariosjpa.findUsuarioEntities()) {
             if (u.getEmail().equals(srtCorreo)) {
                user = u;
            }
        }
        return user;
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Login().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel mensage1;
    private javax.swing.JLabel mensage2;
    // End of variables declaration//GEN-END:variables
}
