/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.PrestamoLibroJpaController;
import bibliotecafusm.EstadoPrestamo;
import bibliotecafusm.PrestamoLibro;
import bibliotecafusm.Usuario;
import java.awt.BorderLayout;
import java.awt.Font;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.font.TextAttribute;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Map;

import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JLabel;


/**
 *
 * @author Jhon Alex
 */
public class Principal extends javax.swing.JFrame  {

    
    private panelRegistroUsuarios p1;
    private panelGestionVideoBeans p2;
    private panelGestionLibros p3;
    
    private panelPrestamoLibros p4;
    private panelPrestamoVideoBean p5;   
    private panelGestionPrestamos p6;
    

    // jpa prestamo libros para validaciones
    //----------------------------------------
    private PrestamoLibroJpaController prestamolibrosjpa;
    
    //-------------------------------------------
    
    private Usuario usuarioLogeado;
    private Login lo;
    
    
    private ventanaPassChange p7;
    
    /**
     * Creates new form Login
     */
    public Principal() {
   
        initComponents();
        
        this.setTitle("Sistema Gestion Prestamos - Biblioteca FUSM Palmira"); 
        
        
        // creacion login
        lo = new Login(this);
        lo.setLayout(new BorderLayout());
        lo.setSize(1340,690);
        lo.setExtendedState(MAXIMIZED_BOTH);
        lo.setLocationRelativeTo(null);
        lo.setVisible(true);
  
        
        panelprincipal.setOpaque(false);
        

   
        // instancia objeto que va guardar la info a la base de datos 
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BibliotecaFUSMPU");
        prestamolibrosjpa = new PrestamoLibroJpaController(emf);
        validacionVencimientoPrestamosLibros();
        
        
            
    p7 = new ventanaPassChange();
    p7.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelprincipal = new javax.swing.JPanel();
        btnadminusuarios = new javax.swing.JButton();
        btngestionvideobeam = new javax.swing.JButton();
        titulopanelseccion = new javax.swing.JLabel();
        btngestionlibros = new javax.swing.JButton();
        btnprestamos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnlibros = new javax.swing.JButton();
        btnvideo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 900, 600));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        panelprincipal.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(panelprincipal);
        panelprincipal.setBounds(200, 120, 1130, 540);

        btnadminusuarios.setText("Administrar Usuarios");
        btnadminusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadminusuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnadminusuarios);
        btnadminusuarios.setBounds(20, 260, 160, 23);

        btngestionvideobeam.setText("Gestion Video Beams");
        btngestionvideobeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngestionvideobeamActionPerformed(evt);
            }
        });
        getContentPane().add(btngestionvideobeam);
        btngestionvideobeam.setBounds(20, 340, 160, 23);

        titulopanelseccion.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        titulopanelseccion.setForeground(new java.awt.Color(204, 204, 204));
        titulopanelseccion.setText("Software biblioteca FUSM Palmira");
        getContentPane().add(titulopanelseccion);
        titulopanelseccion.setBounds(280, 70, 430, 50);

        btngestionlibros.setText("Registro Libros");
        btngestionlibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngestionlibrosActionPerformed(evt);
            }
        });
        getContentPane().add(btngestionlibros);
        btngestionlibros.setBounds(20, 300, 160, 23);

        btnprestamos.setText("Prestamos");
        btnprestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprestamosActionPerformed(evt);
            }
        });
        getContentPane().add(btnprestamos);
        btnprestamos.setBounds(20, 200, 160, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Solicitud Prestamo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 430, 140, 17);

        btnlibros.setText("LIBROS");
        btnlibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlibrosActionPerformed(evt);
            }
        });
        getContentPane().add(btnlibros);
        btnlibros.setBounds(20, 470, 160, 23);

        btnvideo.setText("VIDEO BEAM");
        btnvideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvideoActionPerformed(evt);
            }
        });
        getContentPane().add(btnvideo);
        btnvideo.setBounds(20, 510, 160, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Bienvenido");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1070, 70, 170, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nombres completos");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(960, 90, 280, 17);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/usuario.png"))); // NOI18N
        jLabel5.setText("     ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1260, 60, 50, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/cerrar_sesion.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1300, 10, 20, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Cerrar sesión");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1210, 10, 90, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Cambiar contraseña");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1064, 10, 130, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("|");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1190, 10, 20, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/backfusmprincipal.png"))); // NOI18N
        jLabel1.setText("                ");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1350, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void setUsuario(Usuario user){
        usuarioLogeado = user;
        accesoBotones(usuarioLogeado);
        
        
        if(usuarioLogeado.getIdentificacion().equals("Root")){ 
            jLabel8.setVisible(false);
            jLabel9.setVisible(false); 
        }else{
            jLabel8.setVisible(true);
            jLabel9.setVisible(true); 
        }
       
        panelprincipal.removeAll();
    }
    
    
    // habilita los botones de los modulos para los usuarios docente y estudiente
    public void accesoBotones(Usuario u){
        
        boolean a = true;
        boolean b = false;
        
         jLabel2.setVisible(false);
         jLabel4.setText(u.getTipoUsuario());

        
        if (u.getIdentificacion().equals("Root")) {
            jLabel4.setText(u.getTipoUsuario()+" "+u.getIdentificacion());
        }
 
         
         
        if(u.getTipoUsuario().equals("Estudiante")  ||  u.getTipoUsuario().equals("Docente")){
            a = false;
            b = true;
            
            jLabel2.setVisible(true);
            jLabel3.setText("Bienvenido "+u.getTipoUsuario());
            jLabel4.setText(u.getNombres()+" "+u.getApellidos());            
        }

        btnprestamos.setVisible(a);
        btnadminusuarios.setVisible(a);
        btngestionlibros.setVisible(a);
        btngestionvideobeam.setVisible(a);
        
        btnlibros.setVisible(b);
        btnvideo.setVisible(b);  
    }
    
    
    public void validacionVencimientoPrestamosLibros(){
        
        DateFormat fecha = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaDate =null;
        
        for (PrestamoLibro p : prestamolibrosjpa.findPrestamoLibroEntities()) {
            
            if(p.getFechaMaxDevolucion()!=null){  
            
                fechaDate = p.getFechaMaxDevolucion();
                if (new Date().after(fechaDate)) {
                    // asignar estado vencido al libro que la fecha devolucion sea posterior ala actual
                    p.setEstadoPrestamo(EstadoPrestamo.VENCIDO);
                    
                    try {
                        prestamolibrosjpa.edit(p);
                    } catch (Exception ex) {
                        // Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            
            }
        }
      
    }
    
    

    
    
       
    private void btnadminusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminusuariosActionPerformed
        
        p1 = new panelRegistroUsuarios();
        panelprincipal.removeAll();
        panelprincipal.add(new JLabel("                                                             ")); 
       
        panelprincipal.add(p1);        
        panelprincipal.updateUI();       
        titulopanelseccion.setText("Modulo Administración Usuarios");

    }//GEN-LAST:event_btnadminusuariosActionPerformed

    
    private void btngestionvideobeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngestionvideobeamActionPerformed
        
        p2 = new panelGestionVideoBeans();
        panelprincipal.removeAll();
        panelprincipal.add(new JLabel("                                                             ")); 
       
        panelprincipal.add(p2);
        panelprincipal.updateUI();
        titulopanelseccion.setText("Modulo Gestion Video Beams");
    }//GEN-LAST:event_btngestionvideobeamActionPerformed

    
    private void btngestionlibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngestionlibrosActionPerformed
        
        p3 = new panelGestionLibros();
        panelprincipal.removeAll();
        panelprincipal.add(new JLabel("                                                             ")); 
        
        panelprincipal.add(p3);
        panelprincipal.updateUI();
        titulopanelseccion.setText("Modulo Gestion Libros");
    }//GEN-LAST:event_btngestionlibrosActionPerformed

    private void btnlibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlibrosActionPerformed
               
        p4 = new panelPrestamoLibros(usuarioLogeado);       
        panelprincipal.removeAll();
        panelprincipal.add(new JLabel("                                                             ")); 
       
        panelprincipal.add(p4);
        panelprincipal.updateUI();
        titulopanelseccion.setText("Modulo Prestamo Libros");
    }//GEN-LAST:event_btnlibrosActionPerformed

    private void btnvideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvideoActionPerformed
        
        p5 = new panelPrestamoVideoBean(usuarioLogeado);       
        panelprincipal.removeAll();
        panelprincipal.add(new JLabel("                                                             ")); 
       
        panelprincipal.add(p5);
        panelprincipal.updateUI();
        titulopanelseccion.setText("Modulo Prestamo Video Beam");
    }//GEN-LAST:event_btnvideoActionPerformed

    private void btnprestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprestamosActionPerformed
        
        p6 = new panelGestionPrestamos();       
        panelprincipal.removeAll();
        panelprincipal.add(new JLabel("                                                             ")); 
       
        panelprincipal.add(p6);
        panelprincipal.updateUI();
        titulopanelseccion.setText("Modulo Gestion Prestamos ");
    }//GEN-LAST:event_btnprestamosActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        
        this.setVisible(false);
        lo.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    
    
    
    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
//        this.setVisible(false);
//        lo.setVisible(true);
        System.exit(0); 
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        
        Font font = jLabel7.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        jLabel7.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_jLabel7MouseEntered

 
    
    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
 
    removeUnderline(jLabel7);
    removeUnderline(jLabel8);

    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        Font font = jLabel8.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        jLabel8.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_jLabel8MouseEntered

    

    
    
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        p7.setUserlogin(usuarioLogeado);
        p7.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    // remove el interlineado
    public void removeUnderline(JLabel label){
        Font font1 = label.getFont();
        Map attributes1 = font1.getAttributes();
        attributes1.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE);
        label.setFont(font1.deriveFont(attributes1));
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadminusuarios;
    private javax.swing.JButton btngestionlibros;
    private javax.swing.JButton btngestionvideobeam;
    private javax.swing.JButton btnlibros;
    private javax.swing.JButton btnprestamos;
    private javax.swing.JButton btnvideo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelprincipal;
    private javax.swing.JLabel titulopanelseccion;
    // End of variables declaration//GEN-END:variables



}
